In [1]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.types import *

In [2]:
spark = SparkSession.builder.appName("Notificação Sindrome Gripal").getOrCreate()

In [3]:
spark.conf.set("spark.sql.debug.maxToTringFields", 100)

In [4]:
path = '/media/fabio/compartilhado/ModelingTaskForce/data-notificacao_sindrome_gripal/SG/'
file = path + 'part-00000-054ef0fd-5a08-4ecf-8075-fb00eea43ecd-c000.csv'

In [5]:
df = spark.read.csv(file, header=True, inferSchema=True, sep=',')

In [27]:
df.printSchema()

root
 |-- cbo: string (nullable = true)
 |-- classificacaoFinal: string (nullable = true)
 |-- cnes: string (nullable = true)
 |-- condicoes: string (nullable = true)
 |-- dataEncerramento: string (nullable = true)
 |-- dataInicioSintomas: string (nullable = true)
 |-- dataNascimento: string (nullable = true)
 |-- dataNotificacao: string (nullable = true)
 |-- dataTeste: string (nullable = true)
 |-- estado: string (nullable = true)
 |-- estadoIBGE: string (nullable = true)
 |-- estadoNotificacao: string (nullable = true)
 |-- estadoNotificacaoIBGE: string (nullable = true)
 |-- estadoTeste: string (nullable = true)
 |-- evolucaoCaso: string (nullable = true)
 |-- excluido: string (nullable = true)
 |-- idade: string (nullable = true)
 |-- municipio: string (nullable = true)
 |-- municipioIBGE: string (nullable = true)
 |-- municipioNotificacao: string (nullable = true)
 |-- municipioNotificacaoIBGE: string (nullable = true)
 |-- origem: string (nullable = true)
 |-- paisOrigem: string (nullable = true)
 |-- profissionalSaude: string (nullable = true)
 |-- resultadoTeste: string (nullable = true)
 |-- sexo: string (nullable = true)
 |-- sintomas: string (nullable = true)
 |-- tipoTeste: string (nullable = true)
 |-- validado: string (nullable = true)
 |-- �id: string (nullable = true)

In [34]:
n_col, n_lin = len(df.columns), df.count()

In [35]:
print(f"Shape: {n_col}, {n_lin}")

Shape: 30, 48288827

In [25]:
df.columns

['cbo',
 'classificacaoFinal',
 'cnes',
 'condicoes',
 'dataEncerramento',
 'dataInicioSintomas',
 'dataNascimento',
 'dataNotificacao',
 'dataTeste',
 'estado',
 'estadoIBGE',
 'estadoNotificacao',
 'estadoNotificacaoIBGE',
 'estadoTeste',
 'evolucaoCaso',
 'excluido',
 'idade',
 'municipio',
 'municipioIBGE',
 'municipioNotificacao',
 'municipioNotificacaoIBGE',
 'origem',
 'paisOrigem',
 'profissionalSaude',
 'resultadoTeste',
 'sexo',
 'sintomas',
 'tipoTeste',
 'validado',
 '�id']

In [1]:
187753 + 1 + 25466595 + 11 + 9628946 + 2362904 +  1 + 259 + 14748 + 313015 + 14 + 10301753 + 12827

48288827

In [2]:
25466595/48288827

0.5273806920180522

In [8]:
for c in df.columns:
    df.groupby(c).count().show()

+--------------------+-----+
|                 cbo|count|
+--------------------+-----+
|2612 - Profission...|  377|
|7687 - Encadernad...|    5|
|515105 - Agente C...|   60|
|                7711|  118|
|                7252|   12|
|Teve Contato Com ...|    1|
|            M�canico|    1|
|Comercio/Supermer...|    1|
|        Telemarkeing|    1|
|Comerciante Autonomo|    1|
|Auxiliar De Bibli...|    1|
|    Recursos Humanos|    2|
|  Casa Do Marceneiro|    1|
|Atendente De Loja...|    1|
|          Motoqueiro|    2|
|       Nao De Aplica|    1|
|Funcionaria Publi...|    1|
|Ipuni Auxliar Adm...|    1|
|         Pensionista|    9|
|2524 - Profission...| 1332|
+--------------------+-----+
only showing top 20 rows

+--------------------+--------+
|  classificacaoFinal|   count|
+--------------------+--------+
|Confirmado por Cr...|  187753|
|          Confirmado|       1|
|                null|25466595|
|Confirmado Clinic...|      11|
|Confirmado Labora...| 9628946|
|S�ndrome Gripal N...| 2362904|
|Confirmado Clinic...|       1|
|Confirma��o Cl�ni...|     259|
|Confirma��o Labor...|   14748|
|Confirmado Cl�nic...|  313015|
|Sindrome Gripal N...|      14|
|          Descartado|10301753|
|Confirmado Cl�nic...|   12827|
+--------------------+--------+

+-------+-----+
|   cnes|count|
+-------+-----+
|2736756|   17|
|2572303|    6|
|2578468|    9|
|2239884|    5|
|2516306|   17|
|2588366|   14|
|2084376|    7|
|2001020|    1|
|5352061|    7|
|6634702|   21|
|2397463|    5|
|5939682|    1|
|2246465|    1|
|2690810|    6|
|5701406|    4|
|0154377|    3|
|2143453|    2|
|6513999|    4|
|7294964|    1|
|7541309|    1|
+-------+-----+
only showing top 20 rows

+--------------------+-----+
|           condicoes|count|
+--------------------+-----+
|Doen�as respirat�...|53071|
|Doen�as respirat�...|   28|
|Doen�as renais cr...|    2|
|Cianosesatura��o ...|    4|
|Cefaleia,Adinamia...|    1|
|Dificuldade Para ...|    1|
|Satura��o O2 Meno...|    1|
|Doen�as respirat�...|    2|
|Doen�as card�acas...|   15|
|Doen�as card�acas...|    2|
|Doen�as respirat�...|    1|
|Imunossupress�o, ...|    2|
|Gestante, Doen�as...|    4|
|Portador de doen�...|    1|
|Doen�as renais cr...|    2|
|Diabetes, Doen�as...|  206|
|Doen�as respirat�...|   61|
|Obesidade, Doen�a...|    9|
|Diabetes, Obesida...|    6|
|Doen�as card�acas...|   11|
+--------------------+-----+
only showing top 20 rows

+-------------------+-----+
|   dataEncerramento|count|
+-------------------+-----+
|2020-05-28 00:00:00| 1604|
|2021-01-28 17:00:00|17633|
|2021-01-29 17:00:00| 5144|
|2020-09-07 00:00:00| 1107|
|2020-12-05 00:00:00| 2583|
|2021-05-29 00:00:00|  648|
|2020-12-14 02:00:00|   10|
|2020-12-20 17:00:00|  391|
|2002-08-30 23:00:00|   11|
|2021-03-28 17:00:00|  111|
|2014-02-26 23:00:00|    1|
|2020-12-06 22:00:00|  534|
|2020-08-12 22:30:00|   15|
|2021-04-08 02:00:00|   28|
|2020-06-16 03:00:00|   17|
|2001-07-01 00:00:00|    1|
|2020-12-19 07:00:00|    9|
|2021-02-15 19:00:00|   35|
|2021-04-15 08:00:00|   95|
|2020-08-13 02:00:00|    9|
+-------------------+-----+
only showing top 20 rows

+--------------------+-----+
|  dataInicioSintomas|count|
+--------------------+-----+
|2020-04-08T04:00:...| 1186|
|2020-05-29T03:00:...|70498|
|2020-07-13T05:00:...|  630|
|2020-07-23T04:00:...| 6179|
|2020-11-08T05:00:...| 1149|
|2020-06-02T00:00:...|  421|
|2020-08-22T04:00:...| 5383|
|2021-01-21T00:00:...|  106|
|2021-01-27T19:00:...|   71|
|2021-02-02T12:00:...|  175|
|2021-03-17T11:00:...|   31|
|2021-05-16T04:00:...| 5347|
|2020-07-09T02:00:...|  159|
|2020-12-03T08:00:...|   10|
|2021-01-06T08:00:...|   13|
|2021-01-02T02:00:...| 1490|
|2020-12-12T20:00:...|   20|
|2021-03-26T00:00:...|   82|
|2020-12-24T08:00:...|    9|
|2021-07-16T10:00:...|   24|
+--------------------+-----+
only showing top 20 rows

+-------------------+-----+
|     dataNascimento|count|
+-------------------+-----+
|1985-10-01 20:00:00|   71|
|1983-06-27 20:00:00|   84|
|1972-10-06 20:00:00|   37|
|1976-01-03 20:00:00|   42|
|1992-05-16 20:00:00|   36|
|1979-04-28 20:00:00|   52|
|1996-05-13 20:00:00|   43|
|1993-05-12 20:00:00|   49|
|1992-03-11 20:00:00|   75|
|2013-10-31 20:00:00|   11|
|1997-04-11 20:00:00|   38|
|1964-10-19 20:00:00|   49|
|1984-10-08 20:00:00|   44|
|1965-09-11 20:00:00|   35|
|1969-02-24 20:00:00|   36|
|1961-09-24 20:00:00|   28|
|1989-08-02 20:00:00|   49|
|1989-05-24 20:00:00|   65|
|1996-02-21 20:00:00|   58|
|1986-03-31 20:00:00|   52|
+-------------------+-----+
only showing top 20 rows

+--------------------+-----+
|     dataNotificacao|count|
+--------------------+-----+
|2020-04-14T15:55:...|    2|
|2020-04-27T22:18:...|    2|
|2020-05-20T19:26:...|    2|
|2020-05-29T03:00:...|38881|
|2020-04-08T04:00:...|  564|
|2020-05-28T12:50:...|    2|
|2020-05-25T20:13:...|    2|
|2020-06-02T20:08:...|    2|
|2020-06-04T13:27:...|    2|
|2020-06-04T18:00:...|    2|
|2020-06-09T15:00:...|    2|
|2020-06-08T20:47:...|    2|
|2020-06-08T21:14:...|    2|
|2020-06-08T21:40:...|    2|
|2020-06-13T13:38:...|    2|
|2020-06-02T19:52:...|    2|
|2020-06-16T15:52:...|    2|
|2020-06-18T21:30:...|    2|
|2020-06-19T18:42:...|    2|
|2020-04-29T21:55:...|    2|
+--------------------+-----+
only showing top 20 rows

+--------------------+-----+
|           dataTeste|count|
+--------------------+-----+
|2020-05-29T03:00:...|66322|
|2020-07-13T05:00:...|  872|
|2020-11-08T05:00:...|  513|
|2020-07-23T04:00:...| 7677|
|2020-08-22T04:00:...| 3076|
|2021-01-27T19:00:...|   88|
|2021-03-17T11:00:...|   87|
|2021-05-16T04:00:...| 1461|
|2020-12-03T08:00:...|   16|
|2021-07-16T10:00:...|   42|
|2020-04-08T04:00:...|  327|
|2021-06-08T08:00:...|   12|
|2021-03-26T00:00:...|  345|
|2021-01-02T02:00:...|  761|
|2021-01-06T08:00:...|   38|
|2020-06-02T00:00:...| 2234|
|2021-01-23T06:00:...|   40|
|2021-01-21T00:00:...|  331|
|2020-07-28T21:00:...|   16|
|2020-07-09T02:00:...|   90|
+--------------------+-----+
only showing top 20 rows

+-------------------+--------+
|             estado|   count|
+-------------------+--------+
|     RIO DE JANEIRO| 3006455|
|             PARAN�|  125402|
|  RIO GRANDE DO SUL| 4012200|
|        MATO GROSSO|  800816|
|           AMAZONAS| 1026049|
|            SERGIPE|  509994|
|RIO GRANDE DO NORTE|  999226|
|               null|    1309|
|              CEAR�| 2030452|
|     SANTA CATARINA| 4001682|
|              AMAP�|  230789|
|              PIAU�|  851540|
|       MINAS GERAIS| 4148111|
|          S�O PAULO|10934211|
|           ROND�NIA|  794385|
|              GOI�S| 2015717|
|            ALAGOAS|  733550|
|   DISTRITO FEDERAL|  712681|
|               ACRE|  557365|
|           MARANH�O| 1006396|
+-------------------+--------+
only showing top 20 rows

+----------+--------+
|estadoIBGE|   count|
+----------+--------+
|        51|  800816|
|        15| 1002362|
|        11|  794375|
|        29| 3028320|
|        42| 4001679|
|        22|  851540|
|        28|  509994|
|        16|  230789|
|        52| 2015717|
|        35|10934035|
|        43| 4012132|
|        31| 4148110|
|        27|  733550|
|        17|  475082|
|        26| 2005779|
|        23| 2030345|
|        41|  125303|
|        25|  998950|
|        53|  712681|
|  Feminino|       1|
+----------+--------+
only showing top 20 rows

+-------------------+-------+
|  estadoNotificacao|  count|
+-------------------+-------+
|     RIO DE JANEIRO|2975205|
|             PARAN�|2676045|
|            3301009|      1|
|  RIO GRANDE DO SUL|4000640|
|        MATO GROSSO| 783515|
|           AMAZONAS| 967070|
|            SERGIPE| 505557|
|RIO GRANDE DO NORTE| 987999|
|               null|     99|
|              CEAR�|1942877|
|     SANTA CATARINA|4039720|
|              AMAP�| 221011|
|              PIAU�| 840966|
|       MINAS GERAIS|3819537|
|          S�O PAULO|9212879|
|           ROND�NIA| 792096|
|              GOI�S|1944388|
|            ALAGOAS| 720244|
|   DISTRITO FEDERAL| 687627|
|               ACRE| 541831|
+-------------------+-------+
only showing top 20 rows

+---------------------+-------+
|estadoNotificacaoIBGE|  count|
+---------------------+-------+
|                   51| 783515|
|                   15| 986670|
|                   11| 792096|
|                   29|2960700|
|                   42|4039720|
|                   28| 505557|
|                   22| 840966|
|                   35|9212879|
|                   52|1944388|
|                   16| 221011|
|                   43|4000640|
|                   31|3819537|
|                   27| 720244|
|                   17| 473241|
|                   26|1984611|
|                   23|1942877|
|                   41|2674736|
|                   25| 986159|
|                   53| 687627|
|                   33|2975205|
+---------------------+-------+
only showing top 20 rows

+--------------------+--------+
|         estadoTeste|   count|
+--------------------+--------+
|                null|     528|
|            Coletado| 4334375|
|       pr� diabettes|       1|
|Exame N�o Solicitado| 2818770|
|          Solicitado| 3196527|
|           undefined|       2|
|           Conclu�do|36298982|
|                null| 1639642|
+--------------------+--------+

+--------------------+--------+
|        evolucaoCaso|   count|
+--------------------+--------+
|           Cancelado| 2518520|
|               �bito|   98598|
|            Ignorado| 2619873|
|                null|27075103|
|           Internado|   23914|
|                  44|       1|
|    Internado em UTI|    4851|
|Em tratamento dom...| 1263494|
|                Cura|14684473|
+--------------------+--------+

+--------------------+--------+
|            excluido|   count|
+--------------------+--------+
|Campos dos Goytac...|       1|
|           undefined|48288826|
+--------------------+--------+

+-----+------+
|idade| count|
+-----+------+
|  829|     3|
|  125|    80|
|  944|     1|
|   51|695554|
|    7|195846|
|  124|   115|
|  334|    30|
|  169|    23|
|  272|     3|
|   54|637592|
|   15|307285|
|  234|     4|
|  232|     6|
|  155|    35|
|  154|    40|
|  132|   132|
|  388|     2|
| 2020|     1|
| 1601|     1|
|   11|206621|
+-----+------+
only showing top 20 rows

+--------------------+-----+
|           municipio|count|
+--------------------+-----+
|    Senador Guiomard|17437|
|        Assis Brasil| 9284|
|              Itatim| 2248|
|              Utinga| 4107|
|             Naz�rio| 2889|
|Olho d'�gua das C...| 3333|
|      Benedito Leite| 1438|
|        Al�m Para�ba| 8240|
|           Carrancas|  321|
|              Sardo�|  645|
|           Fronteira| 3066|
|         Piranguinho| 2320|
|            Rio Novo| 1175|
|            Guidoval| 1618|
|             Capara�|  687|
|  Ribas do Rio Pardo| 4773|
|          Livramento| 1924|
|              Pianco|    1|
|             Gravat�|17344|
|Alvorada do Gurgu�ia| 2217|
+--------------------+-----+
only showing top 20 rows

+-------------+-----+
|municipioIBGE|count|
+-------------+-----+
|      1302108| 1670|
|      2916708| 1080|
|      2926301| 8617|
|      2300705| 3819|
|      2108207| 8141|
|      2104073| 2326|
|      3118809| 1517|
|      3145604| 6393|
|      3136405|  468|
|      3166501|  137|
|      3107000|   96|
|      5000906| 1561|
|      5107206| 1628|
|      1502954| 1299|
|      2517001| 1696|
|      2515005|  877|
|      3507803| 3287|
|      3502507| 5011|
|      4126678|   52|
|      4112405|   40|
+-------------+-----+
only showing top 20 rows

+--------------------+-----+
|municipioNotificacao|count|
+--------------------+-----+
|    Senador Guiomard|16909|
|        Assis Brasil| 8894|
|          Livramento| 1900|
|            Araruama|14259|
|        Al�m Para�ba| 9532|
|             Gravat�|15371|
|              Itatim| 2115|
|              Utinga| 4144|
|              Maruim| 1921|
|      Benedito Leite| 1400|
|           Fronteira| 2421|
|          Taquariva�|  599|
|               Apodi|14437|
|Alvorada do Gurgu�ia| 2172|
|            Guidoval| 1241|
|             Capara�|  588|
|             Naz�rio| 2497|
|  Ribas do Rio Pardo| 4661|
|Olho d'�gua das C...| 3170|
|          Itaguatins| 1266|
+--------------------+-----+
only showing top 20 rows

+------------------------+-----+
|municipioNotificacaoIBGE|count|
+------------------------+-----+
|                 3145604| 6367|
|                 2517001| 1827|
|                 1302108| 1499|
|                 2108207| 7993|
|                 2916708| 1019|
|                 2926301| 8275|
|                 3118809| 1631|
|                 2300705| 3563|
|                 4300109| 3311|
|                 1702554| 5324|
|                 2515005|  778|
|                 1502954| 1252|
|                 3107000|   87|
|                 3502507| 3712|
|                 2104073| 2303|
|                 3136405|  447|
|                 3166501|  112|
|                 3503158|  339|
|                 5000906| 1525|
|                 4319372|  754|
+------------------------+-----+
only showing top 20 rows

+--------------------+--------+
|              origem|   count|
+--------------------+--------+
|              RPA-RS|    1106|
|              RPA-ES|       2|
|       aplicacao-web|   29808|
|              RPA-PR|      28|
|Campos dos Goytac...|       1|
|RPA-SC-FLORIANOPOLIS|     843|
|         parse-cloud| 1364466|
|           undefined|46886135|
|                null|    6438|
+--------------------+--------+

+--------------------+-------+
|          paisOrigem|  count|
+--------------------+-------+
|             Bol�via|      4|
|              Fran�a|      3|
|              Italia|      5|
|             Pol�nia|      1|
|            Alemanha|      1|
|                null|1224762|
|           Argentina|      1|
|Territ�rios do Su...|      1|
|             Tun�sia|      1|
|                Peru|      2|
|               China|      3|
|Rep�blica Centro-...|      1|
|               Chile|      2|
|TESTE R�PIDO - AN...|      1|
|              Canad�|      1|
|             Espanha|      1|
|          Bangladesh|      2|
|            Paraguai|     18|
|             Equador|      1|
|       Cor�ia do Sul|      1|
+--------------------+-------+
only showing top 20 rows

+-----------------+--------+
|profissionalSaude|   count|
+-----------------+--------+
|             null|  184729|
|              Sim| 2106053|
|           M�dico|       1|
|              Nao|       2|
|              N�o|45827151|
|        undefined|       2|
|             null|  170889|
+-----------------+--------+

+--------------------+--------+
|      resultadoTeste|   count|
+--------------------+--------+
|                null|      32|
|2020-06-10T00:00:...|       1|
|            Negativo|22513375|
|Inconclusivo ou I...|   80091|
|           undefined|       2|
|            Positivo|12835580|
|                null|12859746|
+--------------------+--------+

+----------+--------+
|      sexo|   count|
+----------+--------+
|         M|       2|
|  Negativo|       1|
|  Feminino|24818233|
|Indefinido|  117645|
| undefined|       2|
|      null|    2888|
| Masculino|23350056|
+----------+--------+

+--------------------+-----+
|            sintomas|count|
+--------------------+-----+
|Febre, Dor de Gar...|29808|
|Tosse, Outros, Do...|24812|
|Outros, Tosse, Di...|  921|
|Dispneia, Febre, ...|18788|
|Febre, Dor de Cab...| 1550|
|Tosse, Febre, Dis...|   17|
|Dor de Cabe�a, Fe...|  479|
|Tosse, Coriza, Do...| 1114|
|Dor de Garganta, ...|    8|
|Dor de Cabe�a, Di...|  207|
|Tosse, Dist�rbios...| 5059|
|Dispneia, Febre, ...| 3854|
|Tosse, Febre, Dor...|  831|
|Dor de Cabe�a, Co...| 1457|
|Dor de Cabe�a, Di...| 1109|
|Tosse, Dor de Gar...|    6|
|Tosse, Febre, Dor...| 5737|
|Dor de Cabe�a, Do...|   28|
|Outros, Dor de Ca...|  185|
|Dor de Cabe�a, To...| 7356|
+--------------------+-----+
only showing top 20 rows

+--------------------+--------+
|           tipoTeste|   count|
+--------------------+--------+
|              RT-PCR|18643915|
|Imunoensaio por E...|   17145|
|        Teste r�pido|      80|
|                null|     540|
|Imunoensaio por E...|   57199|
|TESTE R�PIDO - AN...| 6169779|
|TESTE R�PIDO - AN...|16031113|
|Enzimaimunoensaio...|   42886|
|Enzimaimunoensaio...|   11593|
|Quimioluminesc�nc...|   26641|
|           undefined|       2|
|                null| 7287933|
|           Conclu�do|       1|
+--------------------+--------+

+---------+--------+
| validado|   count|
+---------+--------+
|  3301009|       1|
|undefined|48288826|
+---------+--------+

+----------+-----+
|       �id|count|
+----------+-----+
|D3R4h1MFwi|    2|
|IEClMxXRUT|    2|
|Orm1bv3RxO|    2|
|ZX5xwFHA8E|    2|
|2BJmFB7elQ|    2|
|LR85yxMjze|    2|
|OoZr6OAueW|    2|
|ZzPyHAECj3|    2|
|LpjlOCSk1W|    2|
|Z1RKUjJQEi|    2|
|aoSjA8ewMr|    2|
|lVmfCoSN04|    2|
|BBpnZ1lFg6|    2|
|VFhHrQ8r6x|    2|
|STAEvZY4qt|    2|
|kHbkXNAN7G|    2|
|Y9chkZHQFW|    2|
|ATywAUjyEU|    2|
|rUPCCcRhPG|    2|
|rovPC0bMdE|    2|
+----------+-----+
only showing top 20 rows

In [29]:
nulls = df.select([F.count(F.when(F.isnan(c) | F.col(c).isNull(), c)).alias(c) for c in df.columns]).toPandas()

In [36]:
for c in nulls.columns: print(c, nulls[c][0], (nulls[c][0] * 100) // n_line)

cbo 1265059 2
classificacaoFinal 25466595 52
cnes 1 0
condicoes 1158398 2
dataEncerramento 28693114 59
dataInicioSintomas 0 0
dataNascimento 0 0
dataNotificacao 0 0
dataTeste 0 0
estado 1309 0
estadoIBGE 0 0
estadoNotificacao 99 0
estadoNotificacaoIBGE 0 0
estadoTeste 528 0
evolucaoCaso 27075103 56
excluido 0 0
idade 0 0
municipio 1186 0
municipioIBGE 0 0
municipioNotificacao 0 0
municipioNotificacaoIBGE 0 0
origem 0 0
paisOrigem 1224762 2
profissionalSaude 184729 0
resultadoTeste 32 0
sexo 0 0
sintomas 1856 0
tipoTeste 540 0
validado 0 0
�id 0 0

In [6]:
df.filter((df['sexo'] == 'Feminino') | (df['sexo'] == 'Masculino')).groupby('sexo', 'resultadoTeste').count().show()

+---------+--------------------+--------+
|     sexo|      resultadoTeste|   count|
+---------+--------------------+--------+
| Feminino|                null| 6630148|
| Feminino|            Negativo|11844639|
|Masculino|            Positivo| 6518872|
|Masculino|                null| 6226390|
|Masculino|            Negativo|10570364|
| Feminino|                null|      18|
|Masculino|Inconclusivo ou I...|   34417|
| Feminino|Inconclusivo ou I...|   45672|
| Feminino|            Positivo| 6297756|
|Masculino|                null|      13|
+---------+--------------------+--------+

In [ ]:
df.filter((df['sexo'] == 'Feminino') | (df['sexo'] == 'Masculino')).groupby('sexo', 'resultadoTeste').count().show()

In [9]:
gen_to_number = F.udf(lambda x: {'Feminino': 1, 'Masculino': 2}[x], IntegerType())

In [10]:
age_to_group = F.udf(lambda x: {'0': 4, '1': 4, '2': 4, '3': 4, '4': 4, '5': 509, '6': 509, '7': 509,
        '8': 509, '9': 509, '10': 1014, '11': 1014, '12': 1014, '13': 1014,
        '14': 1014, '15': 1519, '16': 1519, '17': 1519, '18': 1519, '19': 1519,
        '20': 2014, '21': 2014, '22': 2014, '23': 2014, '24': 2014, '25': 2529,
        '26': 2529, '27': 2529, '28': 2529, '29': 2529, '30': 3034, '31': 3034,
        '32': 3034, '33': 3034, '34': 3034, '35': 3539, '36': 3539, '37': 3539,
        '38': 3539, '39': 3539, '40': 4044, '41': 4044, '42': 4044, '43': 4044,
        '44': 4044, '45': 4549, '46': 4549, '47': 4549, '48': 4549, '49': 4549,
        '50': 5054, '51': 5054, '52': 5054, '53': 5054, '54': 5054, '55': 5559,
        '56': 5559, '57': 5559, '58': 5559, '59': 5559, '60': 6064, '61': 6064,
        '62': 6064, '63': 6064, '64': 6064, '65': 6569, '66': 6569, '67': 6569,
        '68': 6569, '69': 6569, '70': 7074, '71': 7074, '72': 7074, '73': 7074,
        '74': 7074, '75': 7579, '76': 7579, '77': 7579, '78': 7579, '79': 7579,
        '80': 8099, '81': 8099, '82': 8099, '83': 8099, '84': 8099, '85': 8099,
        '86': 8099, '87': 8099, '88': 8099, '89': 8099, '90': 8099, '91': 8099,
        '92': 8099, '93': 8099, '94': 8099, '95': 8099, '96': 8099, '97': 8099,
        '98': 8099, '99': 8099}[x], IntegerType())

In [11]:
df = df.withColumn('sexo', gen_to_number(df['sexo']))

In [12]:
df = df.withColumn('faixa_etaria', age_to_group(df['idade']))

In [13]:
df = df.withColumn('dataInicioSintomas', F.col('dataInicioSintomas').cast(DateType()))

In [14]:
df.select('idade', 'faixa_etaria', 'sexo').show(truncate=False)

+-----+------------+----+
|idade|faixa_etaria|sexo|
+-----+------------+----+
|51   |5054        |2   |
|47   |4549        |1   |
|57   |5559        |1   |
|27   |2529        |1   |
|30   |3034        |2   |
|34   |3034        |2   |
|50   |5054        |2   |
|42   |4044        |2   |
|24   |2014        |1   |
|32   |3034        |2   |
|41   |4044        |1   |
|23   |2014        |2   |
|53   |5054        |1   |
|43   |4044        |2   |
|68   |6569        |2   |
|31   |3034        |1   |
|74   |7074        |2   |
|66   |6569        |2   |
|35   |3539        |2   |
|40   |4044        |1   |
+-----+------------+----+
only showing top 20 rows

In [15]:
inv = ['estadoNotificacao', 'estadoNotificacaoIBGE', 'municipioNotificacao', 'dataInicioSintomas', 'municipioNotificacaoIBGE', 'faixa_etaria', 'sexo']

In [95]:
df.groupby('resultadoTeste').count().show()

+--------------------+--------+
|      resultadoTeste|   count|
+--------------------+--------+
|                null|      32|
|2020-06-10T00:00:...|       1|
|            Negativo|22513375|
|Inconclusivo ou I...|   80091|
|           undefined|       2|
|            Positivo|12835580|
|                null|12859746|
+--------------------+--------+

In [98]:
df.filter(df['resultadoTeste'] != 'Positivo').count()

35453215

In [16]:
new_df = df.filter(df['resultadoTeste'] == 'Positivo')

In [100]:
new_df.count()

12835580

In [22]:
new_df.groupby('resultadoTeste', 'sexo').count().show()

PythonException:
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 604, in main
    process()
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 596, in process
    serializer.dump_stream(out_iter, outfile)
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/serializers.py", line 211, in dump_stream
    self.serializer.dump_stream(self._batched(iterator), stream)
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/serializers.py", line 132, in dump_stream
    for obj in iterator:
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/serializers.py", line 200, in _batched
    for item in iterator:
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 450, in mapper
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 450, in <genexpr>
    result = tuple(f(*[a[o] for o in arg_offsets]) for (arg_offsets, f) in udfs)
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/worker.py", line 85, in <lambda>
    return lambda *a: f(*a)
  File "/opt/spark-3.1.1-bin-hadoop3.2/python/lib/pyspark.zip/pyspark/util.py", line 73, in wrapper
    return f(*args, **kwargs)
  File "<ipython-input-9-d92c32f00e8d>", line 1, in <lambda>
KeyError: 'Indefinido'